version: "2.2"

services:      
        db:
                image: "postgres:12"
                ports:
                        - "5432:5432"
                environment:
                        POSTGRES_USER: pi_countries
                        POSTGRES_PASSWORD: 12345
                        POSTGRES_DB: db_name_countries
                volumes:
                        - db:/var/lib/postgresql/data
    
        src:
                container_name: pi_countries
                image: pi_countries
                build:
                        context: .
                depends_on:
                        - db
                ports:
                        - "3001:3001"
                environment:
                        DB_HOST: db
                        DB_PORT: 5432
                        DB_USER: pi_countries
                        DB_PASSWORD: 12345
                        DB_NAME: db_name_countries
                links:
                        - db
                volumes:
                        - ".:/PI_countrie"
                        - "/PI_countrie/node_modules"
volumes:
        db: {}
